### ISSUE TITLE
first run, parse error

### ISSUE THREAD

**Issue by barzilouik** [asvln/tele#1]
Did a normal install with :
> cargo install --git https://github.com/asvln/tele.git

Then added the shell script in my environment as advised, and got a 
> thread 'main' panicked at 'could not create '~/.config/tele/waypoints.json': Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/waypoints.rs:114:13

I created manually the 
>~/.config/tele/waypoints.json

But got the parsing error :
> thread 'main' panicked at 'error deserializing list: Error("EOF while parsing a value", line: 1, column: 0)', src/waypoints.rs:124:9
Init is not done when

Please handle the first run case ! and bravo for this nice tool

**Comment by asvln** [comment]
Fixed this with the v0.1.1 release. Just reinstall with `cargo install --git https://github.com/asvln/tele.git --force` and everything should be working now.

Appreciate the props.
